package Kruskal;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*<pre>
 Class        ShowGraph.java
 Description  A class with the only purpose to show the content of the text
              files and the coresponding graphs.
 Platform     jdk 1.8.0_241; PC Windows 11 
 History Log  
 * @author	  <i>wldeh</i>
 * @version 	%1% %2%
 * @see     	javax.swing.JDialog
 *</pre>
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class ShowGraph extends javax.swing.JDialog {

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Constructor  ShowGraphs()-default constructor
   * Description  Create an instance of the GUI form with predefined image.
   * Date         11/28/2023
   * History Log
   * @author      <i>wldeh</i>
   * @param       parent Frame
   * @param       modal boolean
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public ShowGraph(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Constructor  ShowGraphs()-default constructor
   * Description  Create an instance of the GUI form with predefined image.
   * Date         11/28/2023
   * History Log
   * @author      <i>wldeh</i>
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public ShowGraph(int index) {
    initComponents();
    this.setModal(true);
    this.setResizable(false);
    //this.setTitle("Cities" + index + " Graph");
    displayGraph(index);
  }

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Method       displayGraph()
   * Description  Method to resize and show image of the selected cities graph.
   * @param       index int
   * Date         11/28/2023
   * History Log
   * @author      <i>wldeh</i>
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public void displayGraph(int index) {
    String imageName = "src/Images/WeightedEdges" + index + "MST.png";
    String imageName0 = "src/Images/WeightedEdges" + index + ".png";
    File imagePicture = new File(imageName);
    if (imagePicture.isFile()) {
      // set the dogJLabel to display the dog
      ImageIcon icon = new ImageIcon(imageName);
      Image img = icon.getImage();
      Image newImg = img.getScaledInstance(
        graphsJLabel.getWidth(),
        graphsJLabel.getHeight(),
        Image.SCALE_SMOOTH
      );
      ImageIcon newIcon = new ImageIcon(newImg);
      graphsJLabel.setIcon(newIcon);

      ImageIcon icon0 = new ImageIcon(imageName0);
      Image img0 = icon0.getImage();
      Image newImg0 = img0.getScaledInstance(
        graphsJLabel0.getWidth(),
        graphsJLabel0.getHeight(),
        Image.SCALE_SMOOTH
      );
      ImageIcon newIcon0 = new ImageIcon(newImg0);
      graphsJLabel0.setIcon(newIcon0);
    }

    graphsJLabel.setToolTipText(imageName); //uncomment to show dog
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    graphsJLabel = new javax.swing.JLabel();
    graphsJLabel0 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Cities graph");
    setResizable(false);

    graphsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    graphsJLabel.setIcon(
      new javax.swing.ImageIcon(getClass().getResource("/Images/Cities0.png"))
    ); // NOI18N

    graphsJLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    graphsJLabel0.setIcon(
      new javax.swing.ImageIcon(getClass().getResource("/Images/Cities0.png"))
    ); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(graphsJLabel)
        .addComponent(graphsJLabel0)
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addComponent(graphsJLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(graphsJLabel0)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    pack();
    setLocationRelativeTo(null);
  } // </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel graphsJLabel;
  private javax.swing.JLabel graphsJLabel0;
  // End of variables declaration//GEN-END:variables
}
